### ISSUE TITLE
How do I create a project?

### ISSUE THREAD

**Issue by clov3rly** [amoussard/sftp-deployment#48]
This is a dumb question... but I can't mapToRemote without creating a project. How do I create a project? I have open the folder that I want to map...

**Comment by vtworockman** [comment]
I have this problem too

**Comment by Mathahal** [comment]
I'm also in this situation.
![msg](https://cloud.githubusercontent.com/assets/5163255/6409279/8294bcec-bea4-11e4-9f90-371f03197dcb.png)

**Comment by orlaqp** [comment]
I am having the same issue .. I also downloaded the Project Manager package and save the project but still getting the same message "Create a project before ..."

**Comment by clov3rly** [comment]
Huh, glad it's not just me. 

Atom 0.182.0

**Comment by orlaqp** [comment]
I could really use this feature but not sure what to do to make it work and at this point do not have time to look at the package source code. In the meantime I am still using FileZilla Client.

**Comment by blitzprog** [comment]
I have the same problem. How do I create a project for sftp-deployment?
I was thinking maybe it needs the Project Manager package but after creating a project there it still didn't change anything.

**Comment by xabierarrabal** [comment]
same here

**Comment by xabierarrabal** [comment]
Ok, so i made it work !! It creates a file in the project root file called .remote-sync.json with the following data:

{
  "transport": "scp",
  "uploadOnSave": false,
  "hostname": "ff",
  "port": "22",
  "ignore": [
    ".git/**"
  ]
}

When pushing the button Map to Remote.. i got same error as @Mathahal , The thing is that SFTP is evaluating the variable "atom.project.path" which is not supported anymore by atom. I already had project-manager installed so i expected this package to create that variable, but apparently no. 

I tried so many things, but i think this is what really made it: I took a look at the error messages at the bottom of atom and corrected the deprecated code until i got no error. (You need to restart atom after making the changes in SFTP code, it's very easy because atom tells you what you need to change). After that, i got a Sync:FTP option at the left side of atom bottom bar. See attached image:

![captura de pantalla 2015-03-01 a las 9 05 23](https://cloud.githubusercontent.com/assets/1733884/6429919/7e162a26-bff2-11e4-83f0-4841b8918eb6.png)

The only problem then was that i tried to type in the configuration in the given fields, and it seem not to work (maybe is just a stylish bug), so i pressed the save button and that file i said above was created.

**Comment by chantelope** [comment]
Also having this issue

**Comment by SharpEdgeMarshall** [comment]
same here!!!

**Comment by misterGF** [comment]
+1

**Comment by raugaral** [comment]
the same in Atom 0.184.0

**Comment by matmuchrapna** [comment]
wtf is the project in atom without projects support?

**Comment by aary** [comment]
I can't seem to work around it either..

**Comment by reggi** [comment]
+1 this is madness

**Comment by reggi** [comment]
I dug into the [DeploymentManager.js](https://github.com/amoussard/sftp-deployment/blob/c62107a63fea7cbd7e63aef7466f2acfb4841f08/lib/DeploymentManager.js)

```
console.log(atom)
console.log(atom.project)
console.log(atom.project.path)
```

Of course `atom.project.path` is undefined. I did a find and replace for it and got the "MapToRemote" by doing a find and replace for `atom.project.path` and replacing it with `atom.project.rootDirectories[0].path` all that function did was create a file in my root directory called `deployment-config.json` but the app crapped out when I tried to upload. 

The plugin doesn't seem to offer directory watching anyway :(

**Comment by Pooky** [comment]
I find quick fix. At DeploymentManager.js after line 15 put this code and it should work.

```
// Quick fix
if(atom.appVersion.split(".")[1] > 182){
  atom.project.path = atom.project.rootDirectories[0].path;
}
```

**Comment by Cipa** [comment]
Many thx to @Pooky

**Comment by alanhouser** [comment]
I concure; thanks @Pooky. 
BTW: at first the fix didn't work. I had to restart Atom. Bingo.

**Comment by Pooky** [comment]
@alanhouser You don't have to restart whole atom, you can reload your view by VIEW->RELOAD in menu :)

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D

**Comment by aary** [comment]
I
